spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false
    
server:
  servlet:
    context-path: /
  port: 8761

logging:
  level:
    root: info
    
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eurekaServiceUrlPollIntervalSeconds: 60